# permissions for end users to edit statefuldbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statefuldb-editor-role
rules:
- apiGroups:
  - databases.menirus95.dev
  resources:
  - statefuldbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databases.menirus95.dev
  resources:
  - statefuldbs/status
  verbs:
  - get
